# Generated by Django 3.2 on 2021-04-26 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20210426_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 14, 31, 976489)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='date_solve',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
