# Generated by Django 3.2 on 2021-04-26 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20210426_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 22, 35, 4, 212113)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='maintenance.rooms'),
        ),
    ]
