# Generated by Django 3.2 on 2021-04-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_authords_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityes', to='books.city'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countrys', to='books.country'),
        ),
    ]
